package model.enums;

public enum OrderStatus {
    WAITING_FOR_EXPERT_SUGGESTION,
    WAITING_FOR_SPECIALIST_SELECTION,
    WAITING_FOR_THE_SPECIALIST_TO_COME_TO_YOUR_PLACE,
    STARTED, DONE, PAID
}
